apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: whoami-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: whoami
  namespaceSelector:
    matchNames:
      - devops-challenge
  endpoints:
  - port: http
    path: /
    interval: 15s
